# 
# Dockerfile for TMS Server.
#
# Use cargo during an initial phase to build the executable.
#
# Directory Structure
# -------------------
# TMS server deployment involves subdirectories under the root installation directory.
# When the container is first run a docker volume named tms_server_vol is created.
# In that volumed the root installation directory is /home/tms and its subdirectories are:
#  - tms, which has four subdirectories created during set up.
#  - tms_local, this is where TMS will:
#    (1) on first time startup write the tms-setup.out file that contains administrative secrets
#    (2) read from optional configuration files customized for the host on which TMS executes.
#  - tms_server, contains the binary executable and the resource files copied to TMS_ROOT_DIR during set up.
#
# PHASE 1 - Build executable using cargo
# ===============================================
# Start with rust image for the build
FROM rust:1.96 AS builder

# Set up directory with cargo project
RUN USER=root cargo new --bin tms_server
WORKDIR /tms_server

# Copy build set up
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# Build dependencies for caching
RUN cargo build --release
RUN rm -fr src/*.rs

# Copy source and resources
COPY ./build.rs ./build.rs
COPY ./src ./src
COPY ./resources ./resources
# .git needed for cargo build
COPY ./.git ./.git

# Build release
RUN rm -fr ./target/release/deps/tms_server*
ENV RUST_BACKTRACE=1
RUN cargo build --release

# PHASE 2 - Create final docker image based on debian
# ===================================================
# Switch to final base image
FROM debian:bookworm-slim

# Install less, vim and some required libraries.
RUN apt update && apt install -y libssl-dev libssl3 less vim-tiny coreutils
# Add user tms and create the root tms install directory
RUN useradd -m tms --uid 4873 --shell /bin/bash
RUN mkdir -p /home/tms/tms
RUN mkdir -p /home/tms/tms_local
RUN mkdir -p /home/tms/tms_server
RUN chown -R tms:tms /home/tms
RUN chmod 700 /home/tms/tms
RUN chmod 700 /home/tms/tms_local

USER tms

# Copy the server executable
WORKDIR /home/tms
COPY --from=builder --chown=tms:tms /tms_server/target/release/tms_server ./tms_server/tms_server
RUN chmod 700 ./tms_server/tms_server

# Copy the resource files used during set up.
# Initial startup expects resources to be copied to be under tms_server/resources_src
COPY --from=builder --chown=tms:tms /tms_server/resources ./tms_server/resources_src

# Start the server by default
CMD ["/home/tms/tms_server/tms_server"]

# Example sleep startup
#CMD ["/usr/bin/sleep", "10000"]
