pub mod pubkeys_create;
pub mod pubkeys_retrieve;
pub mod version;
pub mod client_create;
pub mod client_get;
pub mod client_update;
pub mod client_delete;
pub mod client_update_secret;
pub mod client_list;
pub mod rp_login_create;
pub mod rp_login_get;
pub mod rp_login_update;
pub mod rp_login_delete;
pub mod rp_login_list;
pub mod pubkeys_get;
pub mod pubkeys_delete;
pub mod pubkeys_update;
pub mod user_hosts_create;
pub mod user_hosts_get;
pub mod user_hosts_list;
pub mod user_hosts_delete;
pub mod user_hosts_update;
pub mod delegations_create;
pub mod delegations_get;
pub mod delegations_list;
pub mod delegations_delete;
pub mod delegations_update;
// pub mod hosts_create;
// pub mod hosts_get;
// pub mod hosts_delete;
// pub mod hosts_list;
